port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
secret: ""
hosts:
external-ui: '/root/.config/clash/clash-dashboard/'


dns:
  enable: true
  ipv6: false
  listen: :53
  enhanced-mode: redir-host
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
  fallback:
    - tls://dns.rubyfish.cn:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:

proxy-providers:

proxy-groups:

rules: