version: "3"
services:
  clash:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    container_name: clash
    image:  dockerproxy.com/lihang941/clash-tproxy:2.9.7
    restart: always
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      - ./run.sh:/root/.config/clash/run.sh
    networks:
      clash_network:
        ipv4_address: <macvlan可用的自定义的IP地址>
    dns:
      - <主路由dns>
networks:
    clash_network:
      external:
        name: <macvlan别名>

